-- =============================================================================
-- SCRIPT: 01_pos_schema_ddl.sql
-- PURPOSE: Production-Ready Commercial Retail POS Database Schema for Oracle APEX
-- TARGET: Oracle Database 19c / 21c / 23ai / 26.x & Oracle APEX
-- =============================================================================

-- Sequences for Concurrency-Safe Document Numbering
create sequence pos_invoice_seq start with 100001 increment by 1 nocache nocycle;
create sequence pos_purchase_seq start with 200001 increment by 1 nocache nocycle;
create sequence pos_transfer_seq start with 300001 increment by 1 nocache nocycle;
create sequence pos_adjustment_seq start with 400001 increment by 1 nocache nocycle;
create sequence pos_return_seq start with 500001 increment by 1 nocache nocycle;

-- =============================================================================
-- 1. COMPANY & BRANCH STRUCTURE
-- =============================================================================

create table pos_companies (
    id                            number         generated by default on null as identity
                                                 constraint pos_company_pk primary key,
    company_name                  varchar2(255)  not null constraint pos_company_name_uk unique,
    legal_name                    varchar2(255),
    gstin                         varchar2(20),
    pan                           varchar2(20),
    address                       varchar2(4000),
    phone_number                  varchar2(255),
    email                         varchar2(255),
    logo                          blob,
    is_active                     varchar2(1)    default 'Y' not null
                                                 constraint pos_company_active_ck check (is_active in ('Y', 'N')),
    row_version                   integer        not null,
    created_on                    date           not null,
    created_by                    varchar2(255)  not null,
    updated_on                    date           not null,
    updated_by                    varchar2(255)  not null
);

create table pos_branches (
    id                            number         generated by default on null as identity
                                                 constraint pos_branch_pk primary key,
    company_id                    number         not null
                                                 constraint pos_branch_company_fk
                                                 references pos_companies ( id ),
    branch_code                   varchar2(50)   not null,
    branch_name                   varchar2(255)  not null,
    gstin                         varchar2(20),
    address                       varchar2(4000),
    phone_number                  varchar2(255),
    email                         varchar2(255),
    is_active                     varchar2(1)    default 'Y' not null
                                                 constraint pos_branch_active_ck check (is_active in ('Y', 'N')),
    row_version                   integer        not null,
    created_on                    date           not null,
    created_by                    varchar2(255)  not null,
    updated_on                    date           not null,
    updated_by                    varchar2(255)  not null,
    constraint pos_branch_code_uk unique ( company_id, branch_code )
);

-- =============================================================================
-- 2. SECURITY, ROLES & PERMISSIONS
-- =============================================================================

create table pos_roles (
    id                            number         generated by default on null as identity
                                                 constraint pos_role_pk primary key,
    role_name                     varchar2(255)  not null constraint pos_role_name_uk unique,
    description                   varchar2(4000),
    row_version                   integer        not null,
    created_on                    date           not null,
    created_by                    varchar2(255)  not null,
    updated_on                    date           not null,
    updated_by                    varchar2(255)  not null
);

create table pos_permissions (
    id                            number         generated by default on null as identity
                                                 constraint pos_permission_pk primary key,
    permission_code               varchar2(255)  not null constraint pos_permission_code_uk unique,
    description                   varchar2(4000),
    row_version                   integer        not null,
    created_on                    date           not null,
    created_by                    varchar2(255)  not null,
    updated_on                    date           not null,
    updated_by                    varchar2(255)  not null
);

create table pos_role_permissions (
    id                            number         generated by default on null as identity
                                                 constraint pos_role_permission_pk primary key,
    role_id                       number         not null
                                                 constraint pos_role_perm_role_fk
                                                 references pos_roles ( id )
                                                 on delete cascade,
    permission_id                 number         not null
                                                 constraint pos_role_perm_perm_fk
                                                 references pos_permissions ( id )
                                                 on delete cascade,
    can_view                      varchar2(1)    default 'Y' not null,
    can_create                    varchar2(1)    default 'N' not null,
    can_edit                      varchar2(1)    default 'N' not null,
    can_delete                    varchar2(1)    default 'N' not null,
    can_approve                   varchar2(1)    default 'N' not null,
    row_version                   integer        not null,
    created_on                    date           not null,
    created_by                    varchar2(255)  not null,
    updated_on                    date           not null,
    updated_by                    varchar2(255)  not null,
    constraint pos_role_perm_uk unique ( role_id, permission_id )
);

create table pos_users (
    id                            number         generated by default on null as identity
                                                 constraint pos_user_pk primary key,
    company_id                    number         not null
                                                 constraint pos_user_company_fk
                                                 references pos_companies ( id ),
    role_id                       number         not null
                                                 constraint pos_user_role_fk
                                                 references pos_roles ( id ),
    username                      varchar2(255)  not null constraint pos_user_username_uk unique,
    password_hash                 varchar2(255)  not null,
    password_salt                 varchar2(255)  not null,
    first_name                    varchar2(255)  not null,
    last_name                     varchar2(255)  not null,
    email                         varchar2(255),
    phone_number                  varchar2(255),
    is_active                     varchar2(1)    default 'Y' not null
                                                 constraint pos_user_active_ck check (is_active in ('Y', 'N')),
    row_version                   integer        not null,
    created_on                    date           not null,
    created_by                    varchar2(255)  not null,
    updated_on                    date           not null,
    updated_by                    varchar2(255)  not null
);

create table pos_user_branches (
    id                            number         generated by default on null as identity
                                                 constraint pos_user_branch_pk primary key,
    user_id                       number         not null
                                                 constraint pos_user_branch_user_fk
                                                 references pos_users ( id )
                                                 on delete cascade,
    branch_id                     number         not null
                                                 constraint pos_user_branch_branch_fk
                                                 references pos_branches ( id )
                                                 on delete cascade,
    is_default                    varchar2(1)    default 'N' not null,
    row_version                   integer        not null,
    created_on                    date           not null,
    created_by                    varchar2(255)  not null,
    updated_on                    date           not null,
    updated_by                    varchar2(255)  not null,
    constraint pos_user_branch_uk unique ( user_id, branch_id )
);

-- =============================================================================
-- 3. PRODUCT CATALOG MASTER DATA
-- =============================================================================

create table pos_categories (
    id                            number         generated by default on null as identity
                                                 constraint pos_category_pk primary key,
    company_id                    number         not null
                                                 constraint pos_category_company_fk
                                                 references pos_companies ( id ),
    name                          varchar2(255)  not null,
    description                   varchar2(4000),
    is_active                     varchar2(1)    default 'Y' not null
                                                 constraint pos_category_active_ck check (is_active in ('Y', 'N')),
    row_version                   integer        not null,
    created_on                    date           not null,
    created_by                    varchar2(255)  not null,
    updated_on                    date           not null,
    updated_by                    varchar2(255)  not null,
    constraint pos_category_name_uk unique ( company_id, name )
);

create table pos_subcategories (
    id                            number         generated by default on null as identity
                                                 constraint pos_subcategory_pk primary key,
    company_id                    number         not null
                                                 constraint pos_subcategory_company_fk
                                                 references pos_companies ( id ),
    category_id                   number         not null
                                                 constraint pos_subcategory_category_fk
                                                 references pos_categories ( id ),
    name                          varchar2(255)  not null,
    description                   varchar2(4000),
    is_active                     varchar2(1)    default 'Y' not null
                                                 constraint pos_subcategory_active_ck check (is_active in ('Y', 'N')),
    row_version                   integer        not null,
    created_on                    date           not null,
    created_by                    varchar2(255)  not null,
    updated_on                    date           not null,
    updated_by                    varchar2(255)  not null,
    constraint pos_subcategory_name_uk unique ( company_id, category_id, name )
);

create table pos_brands (
    id                            number         generated by default on null as identity
                                                 constraint pos_brand_pk primary key,
    company_id                    number         not null
                                                 constraint pos_brand_company_fk
                                                 references pos_companies ( id ),
    name                          varchar2(255)  not null,
    description                   varchar2(4000),
    is_active                     varchar2(1)    default 'Y' not null
                                                 constraint pos_brand_active_ck check (is_active in ('Y', 'N')),
    row_version                   integer        not null,
    created_on                    date           not null,
    created_by                    varchar2(255)  not null,
    updated_on                    date           not null,
    updated_by                    varchar2(255)  not null,
    constraint pos_brand_name_uk unique ( company_id, name )
);

create table pos_units (
    id                            number         generated by default on null as identity
                                                 constraint pos_unit_pk primary key,
    company_id                    number         not null
                                                 constraint pos_unit_company_fk
                                                 references pos_companies ( id ),
    name                          varchar2(255)  not null,
    short_name                    varchar2(50),
    is_active                     varchar2(1)    default 'Y' not null
                                                 constraint pos_unit_active_ck check (is_active in ('Y', 'N')),
    row_version                   integer        not null,
    created_on                    date           not null,
    created_by                    varchar2(255)  not null,
    updated_on                    date           not null,
    updated_by                    varchar2(255)  not null,
    constraint pos_unit_name_uk unique ( company_id, name )
);

create table pos_taxes (
    id                            number         generated by default on null as identity
                                                 constraint pos_tax_pk primary key,
    company_id                    number         not null
                                                 constraint pos_tax_company_fk
                                                 references pos_companies ( id ),
    tax_name                      varchar2(255)  not null,
    tax_percentage                number(5,2)    not null constraint pos_tax_percentage_ck check (tax_percentage >= 0),
    is_active                     varchar2(1)    default 'Y' not null
                                                 constraint pos_tax_active_ck check (is_active in ('Y', 'N')),
    row_version                   integer        not null,
    created_on                    date           not null,
    created_by                    varchar2(255)  not null,
    updated_on                    date           not null,
    updated_by                    varchar2(255)  not null
);

create table pos_products (
    id                            number         generated by default on null as identity
                                                 constraint pos_product_pk primary key,
    company_id                    number         not null
                                                 constraint pos_product_company_fk
                                                 references pos_companies ( id ),
    product_code                  varchar2(50)   not null,
    name                          varchar2(255)  not null,
    short_name                    varchar2(255),
    description                   varchar2(4000),
    category_id                   number         not null
                                                 constraint pos_product_category_fk
                                                 references pos_categories ( id ),
    subcategory_id                number
                                                 constraint pos_product_subcategory_fk
                                                 references pos_subcategories ( id ),
    brand_id                      number
                                                 constraint pos_product_brand_fk
                                                 references pos_brands ( id ),
    unit_id                       number         not null
                                                 constraint pos_product_unit_fk
                                                 references pos_units ( id ),
    hsn_sac                       varchar2(50),
    tax_id                        number         not null
                                                 constraint pos_product_tax_fk
                                                 references pos_taxes ( id ),
    mrp                           number(18,2)   not null constraint pos_product_mrp_ck check (mrp >= 0),
    purchase_price                number(18,2)   not null constraint pos_product_pprice_ck check (purchase_price >= 0),
    selling_price                 number(18,2)   not null constraint pos_product_sprice_ck check (selling_price >= 0),
    wholesale_price               number(18,2),
    min_stock                     number         default 0 not null constraint pos_product_minstock_ck check (min_stock >= 0),
    max_stock                     number         default 0 not null constraint pos_product_maxstock_ck check (max_stock >= 0),
    reorder_level                 number         default 0 not null constraint pos_product_reorder_ck check (reorder_level >= 0),
    image_url                     varchar2(1000),
    is_active                     varchar2(1)    default 'Y' not null
                                                 constraint pos_product_active_ck check (is_active in ('Y', 'N')),
    batch_applicable              varchar2(1)    default 'N' not null
                                                 constraint pos_product_batch_ck check (batch_applicable in ('Y', 'N')),
    expiry_applicable             varchar2(1)    default 'N' not null
                                                 constraint pos_product_expiry_ck check (expiry_applicable in ('Y', 'N')),
    serial_applicable             varchar2(1)    default 'N' not null
                                                 constraint pos_product_serial_ck check (serial_applicable in ('Y', 'N')),
    row_version                   integer        not null,
    created_on                    date           not null,
    created_by                    varchar2(255)  not null,
    updated_on                    date           not null,
    updated_by                    varchar2(255)  not null,
    constraint pos_product_code_uk unique ( company_id, product_code )
);

create table pos_product_barcodes (
    id                            number         generated by default on null as identity
                                                 constraint pos_prod_barcode_pk primary key,
    product_id                    number         not null
                                                 constraint pos_prod_barcode_product_fk
                                                 references pos_products ( id )
                                                 on delete cascade,
    barcode                       varchar2(255)  not null constraint pos_prod_barcode_uk unique,
    is_primary                    varchar2(1)    default 'N' not null
                                                 constraint pos_prod_barcode_isprimary_ck check (is_primary in ('Y', 'N')),
    row_version                   integer        not null,
    created_on                    date           not null,
    created_by                    varchar2(255)  not null,
    updated_on                    date           not null,
    updated_by                    varchar2(255)  not null
);

create table pos_batches (
    id                            number         generated by default on null as identity
                                                 constraint pos_batch_pk primary key,
    company_id                    number         not null
                                                 constraint pos_batch_company_fk
                                                 references pos_companies ( id ),
    branch_id                     number         not null
                                                 constraint pos_batch_branch_fk
                                                 references pos_branches ( id ),
    product_id                    number         not null
                                                 constraint pos_batch_product_fk
                                                 references pos_products ( id ),
    batch_number                  varchar2(255)  not null,
    mfg_date                      date,
    expiry_date                   date,
    current_stock_quantity        number         default 0 not null constraint pos_batch_stock_ck check (current_stock_quantity >= 0),
    row_version                   integer        not null,
    created_on                    date           not null,
    created_by                    varchar2(255)  not null,
    updated_on                    date           not null,
    updated_by                    varchar2(255)  not null,
    constraint pos_batch_number_uk unique ( company_id, branch_id, product_id, batch_number )
);

-- =============================================================================
-- 4. BUSINESS PARTNERS (CUSTOMERS & SUPPLIERS)
-- =============================================================================

create table pos_customers (
    id                            number         generated by default on null as identity
                                                 constraint pos_customer_pk primary key,
    company_id                    number         not null
                                                 constraint pos_customer_company_fk
                                                 references pos_companies ( id ),
    customer_code                 varchar2(50)   not null,
    name                          varchar2(255)  not null,
    mobile_number                 varchar2(255),
    email                         varchar2(255),
    gstin                         varchar2(20),
    address                       varchar2(4000),
    credit_limit                  number(18,2)   default 0 not null constraint pos_customer_credit_ck check (credit_limit >= 0),
    opening_balance               number(18,2)   default 0 not null,
    is_active                     varchar2(1)    default 'Y' not null
                                                 constraint pos_customer_active_ck check (is_active in ('Y', 'N')),
    customer_type                 varchar2(50)   default 'REGULAR' not null
                                                 constraint pos_customer_type_ck check (customer_type in ('WALK_IN', 'REGULAR', 'WHOLESALE')),
    row_version                   integer        not null,
    created_on                    date           not null,
    created_by                    varchar2(255)  not null,
    updated_on                    date           not null,
    updated_by                    varchar2(255)  not null,
    constraint pos_customer_code_uk unique ( company_id, customer_code )
);

create table pos_suppliers (
    id                            number         generated by default on null as identity
                                                 constraint pos_supplier_pk primary key,
    company_id                    number         not null
                                                 constraint pos_supplier_company_fk
                                                 references pos_companies ( id ),
    supplier_code                 varchar2(50)   not null,
    name                          varchar2(255)  not null,
    mobile_number                 varchar2(255),
    email                         varchar2(255),
    gstin                         varchar2(20),
    address                       varchar2(4000),
    opening_balance               number(18,2)   default 0 not null,
    is_active                     varchar2(1)    default 'Y' not null
                                                 constraint pos_supplier_active_ck check (is_active in ('Y', 'N')),
    row_version                   integer        not null,
    created_on                    date           not null,
    created_by                    varchar2(255)  not null,
    updated_on                    date           not null,
    updated_by                    varchar2(255)  not null,
    constraint pos_supplier_code_uk unique ( company_id, supplier_code )
);

-- =============================================================================
-- 5. SALES TRANSACTIONS & PAYMENTS
-- =============================================================================

create table pos_sales (
    id                            number         generated by default on null as identity
                                                 constraint pos_sale_pk primary key,
    company_id                    number         not null
                                                 constraint pos_sale_company_fk
                                                 references pos_companies ( id ),
    branch_id                     number         not null
                                                 constraint pos_sale_branch_fk
                                                 references pos_branches ( id ),
    invoice_number                varchar2(255)  not null,
    invoice_date                  timestamp      not null,
    customer_id                   number         not null
                                                 constraint pos_sale_customer_fk
                                                 references pos_customers ( id ),
    cashier_id                    number         not null
                                                 constraint pos_sale_cashier_fk
                                                 references pos_users ( id ),
    subtotal                      number(18,2)   not null constraint pos_sale_subtotal_ck check (subtotal >= 0),
    item_discount_amount          number(18,2)   default 0 not null constraint pos_sale_itemdisc_ck check (item_discount_amount >= 0),
    bill_discount_amount          number(18,2)   default 0 not null constraint pos_sale_billdisc_ck check (bill_discount_amount >= 0),
    taxable_amount                number(18,2)   not null constraint pos_sale_taxable_ck check (taxable_amount >= 0),
    tax_amount                    number(18,2)   not null constraint pos_sale_tax_ck check (tax_amount >= 0),
    round_off_amount              number(18,2)   default 0 not null,
    grand_total                   number(18,2)   not null constraint pos_sale_grandtotal_ck check (grand_total >= 0),
    status                        varchar2(50)   not null
                                                 constraint pos_sale_status_ck check (status in ('COMPLETED', 'HOLD', 'PENDING', 'CANCELLED', 'RETURNED')),
    notes                         varchar2(4000),
    cancellation_reason           varchar2(4000),
    cancelled_by_user_id          number
                                                 constraint pos_sale_cancel_user_fk
                                                 references pos_users ( id ),
    cancelled_on_date             timestamp,
    row_version                   integer        not null,
    created_on                    date           not null,
    created_by                    varchar2(255)  not null,
    updated_on                    date           not null,
    updated_by                    varchar2(255)  not null,
    constraint pos_sale_invoice_num_uk unique ( company_id, branch_id, invoice_number )
);

create table pos_sale_items (
    id                            number         generated by default on null as identity
                                                 constraint pos_sale_item_pk primary key,
    sale_id                       number         not null
                                                 constraint pos_sale_item_sale_fk
                                                 references pos_sales ( id ),
    product_id                    number         not null
                                                 constraint pos_sale_item_product_fk
                                                 references pos_products ( id ),
    product_name                  varchar2(255)  not null,
    product_code                  varchar2(50),
    hsn_sac                       varchar2(50),
    quantity                      number         not null constraint pos_sale_item_qty_ck check (quantity > 0),
    unit_price                    number(18,2)   not null constraint pos_sale_item_unitprice_ck check (unit_price >= 0),
    purchase_price                number(18,2)   default 0 not null, -- Cost basis captured at time of sale
    discount_amount               number(18,2)   default 0 not null constraint pos_sale_item_disc_ck check (discount_amount >= 0),
    tax_rate                      number(5,2)    not null constraint pos_sale_item_taxrate_ck check (tax_rate >= 0),
    tax_amount                    number(18,2)   not null constraint pos_sale_item_taxamt_ck check (tax_amount >= 0),
    line_total                    number(18,2)   not null constraint pos_sale_item_linetotal_ck check (line_total >= 0),
    batch_id                      number
                                                 constraint pos_sale_item_batch_fk
                                                 references pos_batches ( id ),
    serial_number                 varchar2(255),
    row_version                   integer        not null,
    created_on                    date           not null,
    created_by                    varchar2(255)  not null,
    updated_on                    date           not null,
    updated_by                    varchar2(255)  not null
);

create table pos_payments (
    id                            number         generated by default on null as identity
                                                 constraint pos_payment_pk primary key,
    company_id                    number         not null
                                                 constraint pos_payment_company_fk
                                                 references pos_companies ( id ),
    branch_id                     number         not null
                                                 constraint pos_payment_branch_fk
                                                 references pos_branches ( id ),
    sale_id                       number         not null
                                                 constraint pos_payment_sale_fk
                                                 references pos_sales ( id ),
    payment_type                  varchar2(50)   not null
                                                 constraint pos_payment_type_ck check (payment_type in ('CASH', 'CARD', 'UPI', 'WALLET', 'CREDIT', 'OTHER')),
    amount_received               number(18,2)   not null constraint pos_payment_amt_ck check (amount_received >= 0),
    change_amount                 number(18,2)   default 0 not null,
    transaction_ref_number        varchar2(255),
    payment_date                  timestamp      not null,
    row_version                   integer        not null,
    created_on                    date           not null,
    created_by                    varchar2(255)  not null,
    updated_on                    date           not null,
    updated_by                    varchar2(255)  not null
);

-- =============================================================================
-- 6. PURCHASES & SUPPLIER PAYMENTS
-- =============================================================================

create table pos_purchases (
    id                            number         generated by default on null as identity
                                                 constraint pos_purchase_pk primary key,
    company_id                    number         not null
                                                 constraint pos_purchase_company_fk
                                                 references pos_companies ( id ),
    branch_id                     number         not null
                                                 constraint pos_purchase_branch_fk
                                                 references pos_branches ( id ),
    supplier_id                   number         not null
                                                 constraint pos_purchase_supplier_fk
                                                 references pos_suppliers ( id ),
    purchase_invoice_number       varchar2(255)  not null,
    purchase_date                 timestamp      not null,
    subtotal                      number(18,2)   not null constraint pos_purchase_subtotal_ck check (subtotal >= 0),
    discount_amount               number(18,2)   default 0 not null constraint pos_purchase_discount_ck check (discount_amount >= 0),
    freight_charges               number(18,2)   default 0 not null constraint pos_purchase_freight_ck check (freight_charges >= 0),
    other_charges                 number(18,2)   default 0 not null constraint pos_purchase_other_ck check (other_charges >= 0),
    tax_amount                    number(18,2)   default 0 not null constraint pos_purchase_tax_ck check (tax_amount >= 0),
    total_amount                  number(18,2)   not null constraint pos_purchase_total_ck check (total_amount >= 0),
    paid_amount                   number(18,2)   default 0 not null,
    outstanding_amount            number(18,2)   default 0 not null,
    status                        varchar2(50)   not null
                                                 constraint pos_purchase_status_ck check (status in ('COMPLETED', 'DRAFT', 'CANCELLED')),
    row_version                   integer        not null,
    created_on                    date           not null,
    created_by                    varchar2(255)  not null,
    updated_on                    date           not null,
    updated_by                    varchar2(255)  not null,
    constraint pos_purchase_invoice_num_uk unique ( company_id, branch_id, purchase_invoice_number )
);

create table pos_purchase_items (
    id                            number         generated by default on null as identity
                                                 constraint pos_purchase_item_pk primary key,
    purchase_id                   number         not null
                                                 constraint pos_purchase_item_purchase_fk
                                                 references pos_purchases ( id ),
    product_id                    number         not null
                                                 constraint pos_purchase_item_product_fk
                                                 references pos_products ( id ),
    product_name                  varchar2(255)  not null,
    product_code                  varchar2(50),
    hsn_sac                       varchar2(50),
    quantity                      number         not null constraint pos_purchase_item_qty_ck check (quantity > 0),
    purchase_rate                 number(18,2)   not null constraint pos_purchase_item_rate_ck check (purchase_rate >= 0),
    mrp                           number(18,2)   not null constraint pos_purchase_item_mrp_ck check (mrp >= 0),
    discount_amount               number(18,2)   default 0 not null constraint pos_purchase_item_disc_ck check (discount_amount >= 0),
    tax_rate                      number(5,2)    not null constraint pos_purchase_item_taxrate_ck check (tax_rate >= 0),
    tax_amount                    number(18,2)   not null constraint pos_purchase_item_taxamt_ck check (tax_amount >= 0),
    line_total                    number(18,2)   not null constraint pos_purchase_item_linetotal_ck check (line_total >= 0),
    batch_id                      number
                                                 constraint pos_purchase_item_batch_fk
                                                 references pos_batches ( id ),
    expiry_date                   date,
    row_version                   integer        not null,
    created_on                    date           not null,
    created_by                    varchar2(255)  not null,
    updated_on                    date           not null,
    updated_by                    varchar2(255)  not null
);

create table pos_purchase_payments (
    id                            number         generated by default on null as identity
                                                 constraint pos_purchase_payment_pk primary key,
    company_id                    number         not null
                                                 constraint pos_purchase_pay_company_fk
                                                 references pos_companies ( id ),
    branch_id                     number         not null
                                                 constraint pos_purchase_pay_branch_fk
                                                 references pos_branches ( id ),
    purchase_id                   number         not null
                                                 constraint pos_purchase_pay_purchase_fk
                                                 references pos_purchases ( id ),
    payment_type                  varchar2(50)   not null
                                                 constraint pos_purchase_pay_type_ck check (payment_type in ('CASH', 'BANK_TRANSFER', 'CHEQUE', 'CREDIT', 'OTHER')),
    amount                        number(18,2)   not null constraint pos_purchase_pay_amt_ck check (amount >= 0),
    payment_date                  timestamp      not null,
    transaction_ref_number        varchar2(255),
    row_version                   integer        not null,
    created_on                    date           not null,
    created_by                    varchar2(255)  not null,
    updated_on                    date           not null,
    updated_by                    varchar2(255)  not null
);

-- =============================================================================
-- 7. SALES & PURCHASE RETURNS
-- =============================================================================

create table pos_sales_returns (
    id                            number         generated by default on null as identity
                                                 constraint pos_sales_return_pk primary key,
    company_id                    number         not null
                                                 constraint pos_sales_return_company_fk
                                                 references pos_companies ( id ),
    branch_id                     number         not null
                                                 constraint pos_sales_return_branch_fk
                                                 references pos_branches ( id ),
    return_number                 varchar2(255)  not null,
    original_sale_id              number
                                                 constraint pos_sales_return_sale_fk
                                                 references pos_sales ( id ),
    return_date                   timestamp      not null,
    customer_id                   number         not null
                                                 constraint pos_sales_return_customer_fk
                                                 references pos_customers ( id ),
    cashier_id                    number         not null
                                                 constraint pos_sales_return_cashier_fk
                                                 references pos_users ( id ),
    total_amount                  number(18,2)   not null constraint pos_sales_return_total_ck check (total_amount >= 0),
    refund_mode                   varchar2(50)   default 'CASH' not null,
    reason                        varchar2(4000),
    status                        varchar2(50)   not null
                                                 constraint pos_sales_return_status_ck check (status in ('COMPLETED', 'PENDING', 'CANCELLED')),
    row_version                   integer        not null,
    created_on                    date           not null,
    created_by                    varchar2(255)  not null,
    updated_on                    date           not null,
    updated_by                    varchar2(255)  not null,
    constraint pos_sales_return_num_uk unique ( company_id, branch_id, return_number )
);

create table pos_sales_return_items (
    id                            number         generated by default on null as identity
                                                 constraint pos_sales_return_item_pk primary key,
    sales_return_id               number         not null
                                                 constraint pos_sales_return_item_sr_fk
                                                 references pos_sales_returns ( id ),
    original_sale_item_id         number
                                                 constraint pos_sales_return_item_origsi_fk
                                                 references pos_sale_items ( id ),
    product_id                    number         not null
                                                 constraint pos_sales_return_item_prod_fk
                                                 references pos_products ( id ),
    returned_quantity             number         not null constraint pos_sales_return_item_qty_ck check (returned_quantity > 0),
    unit_price                    number(18,2)   not null constraint pos_sales_return_item_uprice_ck check (unit_price >= 0),
    tax_rate                      number(5,2)    not null constraint pos_sales_return_item_taxrate_ck check (tax_rate >= 0),
    tax_amount                    number(18,2)   not null constraint pos_sales_return_item_taxamt_ck check (tax_amount >= 0),
    line_total                    number(18,2)   not null constraint pos_sales_return_item_ltotal_ck check (line_total >= 0),
    batch_id                      number
                                                 constraint pos_sales_return_item_batch_fk
                                                 references pos_batches ( id ),
    serial_number                 varchar2(255),
    row_version                   integer        not null,
    created_on                    date           not null,
    created_by                    varchar2(255)  not null,
    updated_on                    date           not null,
    updated_by                    varchar2(255)  not null
);

create table pos_purchase_returns (
    id                            number         generated by default on null as identity
                                                 constraint pos_purchase_return_pk primary key,
    company_id                    number         not null
                                                 constraint pos_purchase_return_company_fk
                                                 references pos_companies ( id ),
    branch_id                     number         not null
                                                 constraint pos_purchase_return_branch_fk
                                                 references pos_branches ( id ),
    return_number                 varchar2(255)  not null,
    original_purchase_id          number
                                                 constraint pos_purchase_return_origp_fk
                                                 references pos_purchases ( id ),
    return_date                   timestamp      not null,
    supplier_id                   number         not null
                                                 constraint pos_purchase_return_supplier_fk
                                                 references pos_suppliers ( id ),
    total_amount                  number(18,2)   not null constraint pos_purchase_return_total_ck check (total_amount >= 0),
    reason                        varchar2(4000),
    status                        varchar2(50)   not null
                                                 constraint pos_purchase_return_status_ck check (status in ('COMPLETED', 'PENDING', 'CANCELLED')),
    row_version                   integer        not null,
    created_on                    date           not null,
    created_by                    varchar2(255)  not null,
    updated_on                    date           not null,
    updated_by                    varchar2(255)  not null,
    constraint pos_purch_return_num_uk unique ( company_id, branch_id, return_number )
);

create table pos_purchase_return_items (
    id                            number         generated by default on null as identity
                                                 constraint pos_purchase_return_item_pk primary key,
    purchase_return_id            number         not null
                                                 constraint pos_purchase_return_item_pr_fk
                                                 references pos_purchase_returns ( id ),
    original_purchase_item_id     number
                                                 constraint pos_purchase_return_item_origpi_fk
                                                 references pos_purchase_items ( id ),
    product_id                    number         not null
                                                 constraint pos_purchase_return_item_prod_fk
                                                 references pos_products ( id ),
    returned_quantity             number         not null constraint pos_purchase_return_item_qty_ck check (returned_quantity > 0),
    unit_price                    number(18,2)   not null constraint pos_purchase_return_item_uprice_ck check (unit_price >= 0),
    tax_rate                      number(5,2)    not null constraint pos_purchase_return_item_taxrate_ck check (tax_rate >= 0),
    tax_amount                    number(18,2)   not null constraint pos_purchase_return_item_taxamt_ck check (tax_amount >= 0),
    line_total                    number(18,2)   not null constraint pos_purchase_return_item_ltotal_ck check (line_total >= 0),
    batch_id                      number
                                                 constraint pos_purchase_return_item_batch_fk
                                                 references pos_batches ( id ),
    row_version                   integer        not null,
    created_on                    date           not null,
    created_by                    varchar2(255)  not null,
    updated_on                    date           not null,
    updated_by                    varchar2(255)  not null
);

-- =============================================================================
-- 8. CENTRAL STOCK LEDGER, TRANSFERS & ADJUSTMENTS
-- =============================================================================

create table pos_stock_transactions (
    id                            number         generated by default on null as identity
                                                 constraint pos_stock_txn_pk primary key,
    company_id                    number         not null
                                                 constraint pos_stock_txn_company_fk
                                                 references pos_companies ( id ),
    branch_id                     number         not null
                                                 constraint pos_stock_txn_branch_fk
                                                 references pos_branches ( id ),
    product_id                    number         not null
                                                 constraint pos_stock_txn_product_fk
                                                 references pos_products ( id ),
    batch_id                      number
                                                 constraint pos_stock_txn_batch_fk
                                                 references pos_batches ( id ),
    transaction_type              varchar2(50)   not null
                                                 constraint pos_stock_txn_type_ck check (transaction_type in (
                                                     'OPENING', 'PURCHASE', 'PURCHASE_RETURN', 'SALE', 
                                                     'SALES_RETURN', 'TRANSFER_IN', 'TRANSFER_OUT', 
                                                     'ADJUSTMENT_IN', 'ADJUSTMENT_OUT'
                                                 )),
    quantity_change               number         not null, -- positive for in, negative for out
    unit_cost                     number(18,2)   default 0 not null,
    transaction_date              timestamp      not null,
    reference_table               varchar2(255),
    reference_id                  number,
    user_id                       number
                                                 constraint pos_stock_txn_user_fk
                                                 references pos_users ( id ),
    remarks                       varchar2(4000),
    row_version                   integer        not null,
    created_on                    date           not null,
    created_by                    varchar2(255)  not null,
    updated_on                    date           not null,
    updated_by                    varchar2(255)  not null
);

create table pos_stock_transfers (
    id                            number         generated by default on null as identity
                                                 constraint pos_stock_transfer_pk primary key,
    company_id                    number         not null
                                                 constraint pos_stock_transfer_company_fk
                                                 references pos_companies ( id ),
    from_branch_id                number         not null
                                                 constraint pos_stock_transfer_fromb_fk
                                                 references pos_branches ( id ),
    to_branch_id                  number         not null
                                                 constraint pos_stock_transfer_tob_fk
                                                 references pos_branches ( id ),
    transfer_date                 timestamp      not null,
    transfer_ref_number           varchar2(255)  not null,
    status                        varchar2(50)   not null
                                                 constraint pos_stock_transfer_status_ck check (status in ('DRAFT', 'SUBMITTED', 'APPROVED', 'COMPLETED', 'CANCELLED')),
    remarks                       varchar2(4000),
    user_id                       number         not null
                                                 constraint pos_stock_transfer_user_fk
                                                 references pos_users ( id ),
    approved_by_user_id           number
                                                 constraint pos_stock_transfer_appr_user_fk
                                                 references pos_users ( id ),
    row_version                   integer        not null,
    created_on                    date           not null,
    created_by                    varchar2(255)  not null,
    updated_on                    date           not null,
    updated_by                    varchar2(255)  not null,
    constraint pos_stock_transfer_num_uk unique ( company_id, transfer_ref_number )
);

create table pos_stock_transfer_items (
    id                            number         generated by default on null as identity
                                                 constraint pos_st_item_pk primary key,
    stock_transfer_id             number         not null
                                                 constraint pos_st_item_transfer_fk
                                                 references pos_stock_transfers ( id )
                                                 on delete cascade,
    product_id                    number         not null
                                                 constraint pos_st_item_product_fk
                                                 references pos_products ( id ),
    quantity                      number         not null constraint pos_st_item_qty_ck check (quantity > 0),
    batch_id                      number
                                                 constraint pos_st_item_batch_fk
                                                 references pos_batches ( id ),
    serial_number                 varchar2(255),
    row_version                   integer        not null,
    created_on                    date           not null,
    created_by                    varchar2(255)  not null,
    updated_on                    date           not null,
    updated_by                    varchar2(255)  not null
);

create table pos_stock_adjustments (
    id                            number         generated by default on null as identity
                                                 constraint pos_stock_adjustment_pk primary key,
    company_id                    number         not null
                                                 constraint pos_stock_adjustment_company_fk
                                                 references pos_companies ( id ),
    branch_id                     number         not null
                                                 constraint pos_stock_adjustment_branch_fk
                                                 references pos_branches ( id ),
    adjustment_ref_number         varchar2(255)  not null,
    adjustment_date               timestamp      not null,
    adjustment_type               varchar2(50)   not null
                                                 constraint pos_stock_adjustment_type_ck check (adjustment_type in ('IN', 'OUT')),
    reason                        varchar2(4000) not null,
    status                        varchar2(50)   not null
                                                 constraint pos_stock_adjustment_status_ck check (status in ('COMPLETED', 'DRAFT', 'CANCELLED')),
    user_id                       number         not null
                                                 constraint pos_stock_adjustment_user_fk
                                                 references pos_users ( id ),
    row_version                   integer        not null,
    created_on                    date           not null,
    created_by                    varchar2(255)  not null,
    updated_on                    date           not null,
    updated_by                    varchar2(255)  not null,
    constraint pos_stock_adjust_num_uk unique ( company_id, branch_id, adjustment_ref_number )
);

create table pos_stock_adjustment_items (
    id                            number         generated by default on null as identity
                                                 constraint pos_sa_item_pk primary key,
    stock_adjustment_id           number         not null
                                                 constraint pos_sa_item_adjustment_fk
                                                 references pos_stock_adjustments ( id )
                                                 on delete cascade,
    product_id                    number         not null
                                                 constraint pos_sa_item_product_fk
                                                 references pos_products ( id ),
    quantity_adjusted             number         not null, -- positive for IN, negative for OUT
    batch_id                      number
                                                 constraint pos_sa_item_batch_fk
                                                 references pos_batches ( id ),
    serial_number                 varchar2(255),
    row_version                   integer        not null,
    created_on                    date           not null,
    created_by                    varchar2(255)  not null,
    updated_on                    date           not null,
    updated_by                    varchar2(255)  not null
);

-- =============================================================================
-- 9. FINANCIAL LEDGERS (CUSTOMER & SUPPLIER)
-- =============================================================================

create table pos_customer_ledger (
    id                            number         generated by default on null as identity
                                                 constraint pos_customer_ledger_pk primary key,
    company_id                    number         not null
                                                 constraint pos_customer_ledger_company_fk
                                                 references pos_companies ( id ),
    branch_id                     number         not null
                                                 constraint pos_customer_ledger_branch_fk
                                                 references pos_branches ( id ),
    customer_id                   number         not null
                                                 constraint pos_customer_ledger_customer_fk
                                                 references pos_customers ( id ),
    transaction_date              timestamp      not null,
    transaction_type              varchar2(50)   not null
                                                 constraint pos_cust_ledger_type_ck check (transaction_type in ('SALE', 'PAYMENT', 'SALES_RETURN_REFUND', 'CREDIT_NOTE', 'OPENING_BALANCE')),
    reference_table               varchar2(255),
    reference_id                  number,
    debit_amount                  number(18,2)   default 0 not null constraint pos_cust_ledger_debit_ck check (debit_amount >= 0),
    credit_amount                 number(18,2)   default 0 not null constraint pos_cust_ledger_credit_ck check (credit_amount >= 0),
    current_balance               number(18,2)   not null,
    remarks                       varchar2(4000),
    user_id                       number
                                                 constraint pos_customer_ledger_user_fk
                                                 references pos_users ( id ),
    row_version                   integer        not null,
    created_on                    date           not null,
    created_by                    varchar2(255)  not null,
    updated_on                    date           not null,
    updated_by                    varchar2(255)  not null
);

create table pos_supplier_ledger (
    id                            number         generated by default on null as identity
                                                 constraint pos_supplier_ledger_pk primary key,
    company_id                    number         not null
                                                 constraint pos_supplier_ledger_company_fk
                                                 references pos_companies ( id ),
    branch_id                     number         not null
                                                 constraint pos_supplier_ledger_branch_fk
                                                 references pos_branches ( id ),
    supplier_id                   number         not null
                                                 constraint pos_supplier_ledger_supplier_fk
                                                 references pos_suppliers ( id ),
    transaction_date              timestamp      not null,
    transaction_type              varchar2(50)   not null
                                                 constraint pos_supp_ledger_type_ck check (transaction_type in ('PURCHASE', 'PAYMENT', 'PURCHASE_RETURN_REFUND', 'DEBIT_NOTE', 'OPENING_BALANCE')),
    reference_table               varchar2(255),
    reference_id                  number,
    debit_amount                  number(18,2)   default 0 not null constraint pos_supp_ledger_debit_ck check (debit_amount >= 0),
    credit_amount                 number(18,2)   default 0 not null constraint pos_supp_ledger_credit_ck check (credit_amount >= 0),
    current_balance               number(18,2)   not null,
    remarks                       varchar2(4000),
    user_id                       number
                                                 constraint pos_supplier_ledger_user_fk
                                                 references pos_users ( id ),
    row_version                   integer        not null,
    created_on                    date           not null,
    created_by                    varchar2(255)  not null,
    updated_on                    date           not null,
    updated_by                    varchar2(255)  not null
);

-- =============================================================================
-- 10. CONFIGURATION & AUDIT TRAIL
-- =============================================================================

create table pos_settings (
    id                            number         generated by default on null as identity
                                                 constraint pos_setting_pk primary key,
    company_id                    number         not null
                                                 constraint pos_setting_company_fk
                                                 references pos_companies ( id ),
    branch_id                     number, -- Null for company-wide settings
    setting_key                   varchar2(255)  not null,
    setting_value                 varchar2(4000),
    description                   varchar2(4000),
    row_version                   integer        not null,
    created_on                    date           not null,
    created_by                    varchar2(255)  not null,
    updated_on                    date           not null,
    updated_by                    varchar2(255)  not null,
    constraint pos_setting_key_uk unique ( company_id, branch_id, setting_key )
);

create table pos_audit_log (
    id                            number         generated by default on null as identity
                                                 constraint pos_audit_log_pk primary key,
    company_id                    number
                                                 constraint pos_audit_log_company_fk
                                                 references pos_companies ( id ),
    branch_id                     number
                                                 constraint pos_audit_log_branch_fk
                                                 references pos_branches ( id ),
    user_id                       number
                                                 constraint pos_audit_log_user_fk
                                                 references pos_users ( id ),
    action_type                   varchar2(255)  not null,
    table_name                    varchar2(255),
    record_id                     number,
    old_value                     clob,
    new_value                     clob,
    action_timestamp              timestamp      not null,
    ip_address                    varchar2(255),
    browser_info                  varchar2(4000),
    remarks                       varchar2(4000),
    row_version                   integer        not null,
    created_on                    date           not null,
    created_by                    varchar2(255)  not null,
    updated_on                    date           not null,
    updated_by                    varchar2(255)  not null
);

-- =============================================================================
-- 11. INDEXES (FIXED & OPTIMIZED FOR LARGE RETAIL DATASETS)
-- =============================================================================

create index pos_branches_indx_1 on pos_branches ( company_id );
create index pos_role_permissions_indx_1 on pos_role_permissions ( role_id );
create index pos_role_permissions_indx_2 on pos_role_permissions ( permission_id );
create index pos_users_indx_1 on pos_users ( company_id );
create index pos_users_indx_2 on pos_users ( role_id );
create index pos_user_branches_indx_1 on pos_user_branches ( user_id );
create index pos_user_branches_indx_2 on pos_user_branches ( branch_id );
create index pos_categories_indx_1 on pos_categories ( company_id );
create index pos_subcategories_indx_1 on pos_subcategories ( company_id );
create index pos_subcategories_indx_2 on pos_subcategories ( category_id );
create index pos_brands_indx_1 on pos_brands ( company_id );
create index pos_units_indx_1 on pos_units ( company_id );
create index pos_taxes_indx_1 on pos_taxes ( company_id );
create index pos_products_indx_1 on pos_products ( company_id );
create index pos_products_indx_2 on pos_products ( category_id );
create index pos_products_indx_3 on pos_products ( subcategory_id );
create index pos_products_indx_4 on pos_products ( brand_id );
create index pos_products_indx_5 on pos_products ( unit_id );
create index pos_products_indx_6 on pos_products ( tax_id );
create index pos_product_barcodes_indx_1 on pos_product_barcodes ( product_id );
create index pos_customers_indx_1 on pos_customers ( company_id );
create index pos_suppliers_indx_1 on pos_suppliers ( company_id );
create index pos_batches_indx_1 on pos_batches ( company_id );
create index pos_batches_indx_2 on pos_batches ( branch_id );
create index pos_batches_indx_3 on pos_batches ( product_id );
create index pos_sales_indx_1 on pos_sales ( company_id );
create index pos_sales_indx_2 on pos_sales ( branch_id );
create index pos_sales_indx_3 on pos_sales ( customer_id );
create index pos_sales_indx_4 on pos_sales ( cashier_id );
create index pos_sales_indx_5 on pos_sales ( invoice_date );
create index pos_sales_item_indx_1 on pos_sale_items ( sale_id );
create index pos_sales_item_indx_2 on pos_sale_items ( product_id );
create index pos_sales_item_indx_3 on pos_sale_items ( batch_id );
create index pos_payments_indx_1 on pos_payments ( company_id );
create index pos_payments_indx_2 on pos_payments ( branch_id );
create index pos_payments_indx_3 on pos_payments ( sale_id );
create index pos_purchases_indx_1 on pos_purchases ( company_id );
create index pos_purchases_indx_2 on pos_purchases ( branch_id );
create index pos_purchases_indx_3 on pos_purchases ( supplier_id );
create index pos_purchases_indx_4 on pos_purchases ( purchase_date );
create index pos_purchase_item_indx_1 on pos_purchase_items ( purchase_id );
create index pos_purchase_item_indx_2 on pos_purchase_items ( product_id );
create index pos_purchase_item_indx_3 on pos_purchase_items ( batch_id );
create index pos_purchase_payments_indx_1 on pos_purchase_payments ( company_id );
create index pos_purchase_payments_indx_2 on pos_purchase_payments ( branch_id );
create index pos_purchase_payments_indx_3 on pos_purchase_payments ( purchase_id );
create index pos_sales_returns_indx_1 on pos_sales_returns ( company_id );
create index pos_sales_returns_indx_2 on pos_sales_returns ( branch_id );
create index pos_sales_returns_indx_3 on pos_sales_returns ( original_sale_id );
create index pos_sales_returns_indx_4 on pos_sales_returns ( customer_id );
create index pos_sales_returns_indx_5 on pos_sales_returns ( cashier_id );
create index pos_sales_return_items_indx_1 on pos_sales_return_items ( sales_return_id );
create index pos_sales_return_items_indx_2 on pos_sales_return_items ( original_sale_item_id );
create index pos_sales_return_items_indx_3 on pos_sales_return_items ( product_id );
create index pos_sales_return_items_indx_4 on pos_sales_return_items ( batch_id );
create index pos_purchase_returns_indx_1 on pos_purchase_returns ( company_id );
create index pos_purchase_returns_indx_2 on pos_purchase_returns ( branch_id );
create index pos_purchase_returns_indx_3 on pos_purchase_returns ( original_purchase_id );
create index pos_purchase_returns_indx_4 on pos_purchase_returns ( supplier_id );
create index pos_purchase_return_items_indx_1 on pos_purchase_return_items ( purchase_return_id );
create index pos_purchase_return_items_indx_2 on pos_purchase_return_items ( original_purchase_item_id );
create index pos_purchase_return_items_indx_3 on pos_purchase_return_items ( product_id );
create index pos_purchase_return_items_indx_4 on pos_purchase_return_items ( batch_id );
create index pos_stock_transactions_indx_1 on pos_stock_transactions ( company_id );
create index pos_stock_transactions_indx_2 on pos_stock_transactions ( branch_id );
create index pos_stock_transactions_indx_3 on pos_stock_transactions ( product_id );
create index pos_stock_transactions_indx_4 on pos_stock_transactions ( batch_id );
create index pos_stock_transactions_indx_5 on pos_stock_transactions ( reference_table, reference_id );
create index pos_stock_transactions_indx_6 on pos_stock_transactions ( user_id );
create index pos_stock_transfers_indx_1 on pos_stock_transfers ( company_id );
create index pos_stock_transfers_indx_2 on pos_stock_transfers ( from_branch_id );
create index pos_stock_transfers_indx_3 on pos_stock_transfers ( to_branch_id );
create index pos_stock_transfers_indx_4 on pos_stock_transfers ( user_id );
create index pos_st_items_indx_1 on pos_stock_transfer_items ( stock_transfer_id );
create index pos_st_items_indx_2 on pos_stock_transfer_items ( product_id );
create index pos_st_items_indx_3 on pos_stock_transfer_items ( batch_id );
create index pos_stock_adjustments_indx_1 on pos_stock_adjustments ( company_id );
create index pos_stock_adjustments_indx_2 on pos_stock_adjustments ( branch_id );
create index pos_stock_adjustments_indx_3 on pos_stock_adjustments ( user_id );
create index pos_sa_items_indx_1 on pos_stock_adjustment_items ( stock_adjustment_id );
create index pos_sa_items_indx_2 on pos_stock_adjustment_items ( product_id );
-- FIX: Corrected typo from POS.txt line 1051 where table was mistakenly named pos_sa_items
create index pos_sa_items_indx_3 on pos_stock_adjustment_items ( batch_id );
create index pos_customer_ledger_indx_1 on pos_customer_ledger ( company_id );
create index pos_customer_ledger_indx_2 on pos_customer_ledger ( branch_id );
create index pos_customer_ledger_indx_3 on pos_customer_ledger ( customer_id );
create index pos_customer_ledger_indx_4 on pos_customer_ledger ( reference_table, reference_id );
create index pos_customer_ledger_indx_5 on pos_customer_ledger ( user_id );
create index pos_supplier_ledger_indx_1 on pos_supplier_ledger ( company_id );
create index pos_supplier_ledger_indx_2 on pos_supplier_ledger ( branch_id );
create index pos_supplier_ledger_indx_3 on pos_supplier_ledger ( supplier_id );
create index pos_supplier_ledger_indx_4 on pos_supplier_ledger ( reference_table, reference_id );
create index pos_supplier_ledger_indx_5 on pos_supplier_ledger ( user_id );
create index pos_settings_indx_1 on pos_settings ( company_id );
create index pos_settings_indx_2 on pos_settings ( branch_id );
create index pos_audit_log_indx_1 on pos_audit_log ( company_id );
create index pos_audit_log_indx_2 on pos_audit_log ( branch_id );
create index pos_audit_log_indx_3 on pos_audit_log ( user_id );
create index pos_audit_log_indx_4 on pos_audit_log ( table_name, record_id );

-- =============================================================================
-- 12. AUDIT & ROW VERSIONING TRIGGERS (BIU)
-- =============================================================================

create or replace trigger pos_companies_biu
    before insert or update on pos_companies for each row
begin
    :new.updated_on := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION', 'APP_USER'), user);
    if inserting then
        :new.row_version := 1;
        :new.created_on  := :new.updated_on;
        :new.created_by  := :new.updated_by;
    elsif updating then
        :new.row_version := nvl(:old.row_version, 0) + 1;
    end if;
end;
/

create or replace trigger pos_branches_biu
    before insert or update on pos_branches for each row
begin
    :new.updated_on := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION', 'APP_USER'), user);
    if inserting then
        :new.row_version := 1;
        :new.created_on  := :new.updated_on;
        :new.created_by  := :new.updated_by;
    elsif updating then
        :new.row_version := nvl(:old.row_version, 0) + 1;
    end if;
end;
/

create or replace trigger pos_roles_biu
    before insert or update on pos_roles for each row
begin
    :new.updated_on := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION', 'APP_USER'), user);
    if inserting then
        :new.row_version := 1;
        :new.created_on  := :new.updated_on;
        :new.created_by  := :new.updated_by;
    elsif updating then
        :new.row_version := nvl(:old.row_version, 0) + 1;
    end if;
end;
/

create or replace trigger pos_permissions_biu
    before insert or update on pos_permissions for each row
begin
    :new.updated_on := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION', 'APP_USER'), user);
    if inserting then
        :new.row_version := 1;
        :new.created_on  := :new.updated_on;
        :new.created_by  := :new.updated_by;
    elsif updating then
        :new.row_version := nvl(:old.row_version, 0) + 1;
    end if;
end;
/

create or replace trigger pos_role_permissions_biu
    before insert or update on pos_role_permissions for each row
begin
    :new.updated_on := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION', 'APP_USER'), user);
    if inserting then
        :new.row_version := 1;
        :new.created_on  := :new.updated_on;
        :new.created_by  := :new.updated_by;
    elsif updating then
        :new.row_version := nvl(:old.row_version, 0) + 1;
    end if;
end;
/

create or replace trigger pos_users_biu
    before insert or update on pos_users for each row
begin
    :new.updated_on := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION', 'APP_USER'), user);
    if inserting then
        :new.row_version := 1;
        :new.created_on  := :new.updated_on;
        :new.created_by  := :new.updated_by;
    elsif updating then
        :new.row_version := nvl(:old.row_version, 0) + 1;
    end if;
end;
/

create or replace trigger pos_user_branches_biu
    before insert or update on pos_user_branches for each row
begin
    :new.updated_on := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION', 'APP_USER'), user);
    if inserting then
        :new.row_version := 1;
        :new.created_on  := :new.updated_on;
        :new.created_by  := :new.updated_by;
    elsif updating then
        :new.row_version := nvl(:old.row_version, 0) + 1;
    end if;
end;
/

create or replace trigger pos_categories_biu
    before insert or update on pos_categories for each row
begin
    :new.updated_on := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION', 'APP_USER'), user);
    if inserting then
        :new.row_version := 1;
        :new.created_on  := :new.updated_on;
        :new.created_by  := :new.updated_by;
    elsif updating then
        :new.row_version := nvl(:old.row_version, 0) + 1;
    end if;
end;
/

create or replace trigger pos_subcategories_biu
    before insert or update on pos_subcategories for each row
begin
    :new.updated_on := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION', 'APP_USER'), user);
    if inserting then
        :new.row_version := 1;
        :new.created_on  := :new.updated_on;
        :new.created_by  := :new.updated_by;
    elsif updating then
        :new.row_version := nvl(:old.row_version, 0) + 1;
    end if;
end;
/

create or replace trigger pos_brands_biu
    before insert or update on pos_brands for each row
begin
    :new.updated_on := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION', 'APP_USER'), user);
    if inserting then
        :new.row_version := 1;
        :new.created_on  := :new.updated_on;
        :new.created_by  := :new.updated_by;
    elsif updating then
        :new.row_version := nvl(:old.row_version, 0) + 1;
    end if;
end;
/

create or replace trigger pos_units_biu
    before insert or update on pos_units for each row
begin
    :new.updated_on := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION', 'APP_USER'), user);
    if inserting then
        :new.row_version := 1;
        :new.created_on  := :new.updated_on;
        :new.created_by  := :new.updated_by;
    elsif updating then
        :new.row_version := nvl(:old.row_version, 0) + 1;
    end if;
end;
/

create or replace trigger pos_taxes_biu
    before insert or update on pos_taxes for each row
begin
    :new.updated_on := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION', 'APP_USER'), user);
    if inserting then
        :new.row_version := 1;
        :new.created_on  := :new.updated_on;
        :new.created_by  := :new.updated_by;
    elsif updating then
        :new.row_version := nvl(:old.row_version, 0) + 1;
    end if;
end;
/

create or replace trigger pos_products_biu
    before insert or update on pos_products for each row
begin
    :new.updated_on := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION', 'APP_USER'), user);
    if inserting then
        :new.row_version := 1;
        :new.created_on  := :new.updated_on;
        :new.created_by  := :new.updated_by;
    elsif updating then
        :new.row_version := nvl(:old.row_version, 0) + 1;
    end if;
end;
/

create or replace trigger pos_product_barcodes_biu
    before insert or update on pos_product_barcodes for each row
begin
    :new.updated_on := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION', 'APP_USER'), user);
    if inserting then
        :new.row_version := 1;
        :new.created_on  := :new.updated_on;
        :new.created_by  := :new.updated_by;
    elsif updating then
        :new.row_version := nvl(:old.row_version, 0) + 1;
    end if;
end;
/

create or replace trigger pos_customers_biu
    before insert or update on pos_customers for each row
begin
    :new.updated_on := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION', 'APP_USER'), user);
    if inserting then
        :new.row_version := 1;
        :new.created_on  := :new.updated_on;
        :new.created_by  := :new.updated_by;
    elsif updating then
        :new.row_version := nvl(:old.row_version, 0) + 1;
    end if;
end;
/

create or replace trigger pos_suppliers_biu
    before insert or update on pos_suppliers for each row
begin
    :new.updated_on := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION', 'APP_USER'), user);
    if inserting then
        :new.row_version := 1;
        :new.created_on  := :new.updated_on;
        :new.created_by  := :new.updated_by;
    elsif updating then
        :new.row_version := nvl(:old.row_version, 0) + 1;
    end if;
end;
/

create or replace trigger pos_batches_biu
    before insert or update on pos_batches for each row
begin
    :new.updated_on := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION', 'APP_USER'), user);
    if inserting then
        :new.row_version := 1;
        :new.created_on  := :new.updated_on;
        :new.created_by  := :new.updated_by;
    elsif updating then
        :new.row_version := nvl(:old.row_version, 0) + 1;
    end if;
end;
/

create or replace trigger pos_sales_biu
    before insert or update on pos_sales for each row
begin
    :new.updated_on := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION', 'APP_USER'), user);
    if inserting then
        :new.row_version := 1;
        :new.created_on  := :new.updated_on;
        :new.created_by  := :new.updated_by;
    elsif updating then
        :new.row_version := nvl(:old.row_version, 0) + 1;
    end if;
end;
/

create or replace trigger pos_sale_items_biu
    before insert or update on pos_sale_items for each row
begin
    :new.updated_on := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION', 'APP_USER'), user);
    if inserting then
        :new.row_version := 1;
        :new.created_on  := :new.updated_on;
        :new.created_by  := :new.updated_by;
    elsif updating then
        :new.row_version := nvl(:old.row_version, 0) + 1;
    end if;
end;
/

create or replace trigger pos_payments_biu
    before insert or update on pos_payments for each row
begin
    :new.updated_on := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION', 'APP_USER'), user);
    if inserting then
        :new.row_version := 1;
        :new.created_on  := :new.updated_on;
        :new.created_by  := :new.updated_by;
    elsif updating then
        :new.row_version := nvl(:old.row_version, 0) + 1;
    end if;
end;
/

create or replace trigger pos_purchases_biu
    before insert or update on pos_purchases for each row
begin
    :new.updated_on := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION', 'APP_USER'), user);
    if inserting then
        :new.row_version := 1;
        :new.created_on  := :new.updated_on;
        :new.created_by  := :new.updated_by;
    elsif updating then
        :new.row_version := nvl(:old.row_version, 0) + 1;
    end if;
end;
/

create or replace trigger pos_purchase_items_biu
    before insert or update on pos_purchase_items for each row
begin
    :new.updated_on := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION', 'APP_USER'), user);
    if inserting then
        :new.row_version := 1;
        :new.created_on  := :new.updated_on;
        :new.created_by  := :new.updated_by;
    elsif updating then
        :new.row_version := nvl(:old.row_version, 0) + 1;
    end if;
end;
/

create or replace trigger pos_purchase_payments_biu
    before insert or update on pos_purchase_payments for each row
begin
    :new.updated_on := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION', 'APP_USER'), user);
    if inserting then
        :new.row_version := 1;
        :new.created_on  := :new.updated_on;
        :new.created_by  := :new.updated_by;
    elsif updating then
        :new.row_version := nvl(:old.row_version, 0) + 1;
    end if;
end;
/

create or replace trigger pos_sales_returns_biu
    before insert or update on pos_sales_returns for each row
begin
    :new.updated_on := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION', 'APP_USER'), user);
    if inserting then
        :new.row_version := 1;
        :new.created_on  := :new.updated_on;
        :new.created_by  := :new.updated_by;
    elsif updating then
        :new.row_version := nvl(:old.row_version, 0) + 1;
    end if;
end;
/

create or replace trigger pos_sales_return_items_biu
    before insert or update on pos_sales_return_items for each row
begin
    :new.updated_on := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION', 'APP_USER'), user);
    if inserting then
        :new.row_version := 1;
        :new.created_on  := :new.updated_on;
        :new.created_by  := :new.updated_by;
    elsif updating then
        :new.row_version := nvl(:old.row_version, 0) + 1;
    end if;
end;
/

create or replace trigger pos_purchase_returns_biu
    before insert or update on pos_purchase_returns for each row
begin
    :new.updated_on := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION', 'APP_USER'), user);
    if inserting then
        :new.row_version := 1;
        :new.created_on  := :new.updated_on;
        :new.created_by  := :new.updated_by;
    elsif updating then
        :new.row_version := nvl(:old.row_version, 0) + 1;
    end if;
end;
/

create or replace trigger pos_purchase_return_items_biu
    before insert or update on pos_purchase_return_items for each row
begin
    :new.updated_on := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION', 'APP_USER'), user);
    if inserting then
        :new.row_version := 1;
        :new.created_on  := :new.updated_on;
        :new.created_by  := :new.updated_by;
    elsif updating then
        :new.row_version := nvl(:old.row_version, 0) + 1;
    end if;
end;
/

create or replace trigger pos_stock_transactions_biu
    before insert or update on pos_stock_transactions for each row
begin
    :new.updated_on := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION', 'APP_USER'), user);
    if inserting then
        :new.row_version := 1;
        :new.created_on  := :new.updated_on;
        :new.created_by  := :new.updated_by;
    elsif updating then
        :new.row_version := nvl(:old.row_version, 0) + 1;
    end if;
end;
/

create or replace trigger pos_stock_transfers_biu
    before insert or update on pos_stock_transfers for each row
begin
    :new.updated_on := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION', 'APP_USER'), user);
    if inserting then
        :new.row_version := 1;
        :new.created_on  := :new.updated_on;
        :new.created_by  := :new.updated_by;
    elsif updating then
        :new.row_version := nvl(:old.row_version, 0) + 1;
    end if;
end;
/

create or replace trigger pos_stock_transfer_items_biu
    before insert or update on pos_stock_transfer_items for each row
begin
    :new.updated_on := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION', 'APP_USER'), user);
    if inserting then
        :new.row_version := 1;
        :new.created_on  := :new.updated_on;
        :new.created_by  := :new.updated_by;
    elsif updating then
        :new.row_version := nvl(:old.row_version, 0) + 1;
    end if;
end;
/

create or replace trigger pos_stock_adjustments_biu
    before insert or update on pos_stock_adjustments for each row
begin
    :new.updated_on := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION', 'APP_USER'), user);
    if inserting then
        :new.row_version := 1;
        :new.created_on  := :new.updated_on;
        :new.created_by  := :new.updated_by;
    elsif updating then
        :new.row_version := nvl(:old.row_version, 0) + 1;
    end if;
end;
/

create or replace trigger pos_stock_adjustment_items_biu
    before insert or update on pos_stock_adjustment_items for each row
begin
    :new.updated_on := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION', 'APP_USER'), user);
    if inserting then
        :new.row_version := 1;
        :new.created_on  := :new.updated_on;
        :new.created_by  := :new.updated_by;
    elsif updating then
        :new.row_version := nvl(:old.row_version, 0) + 1;
    end if;
end;
/

create or replace trigger pos_customer_ledger_biu
    before insert or update on pos_customer_ledger for each row
begin
    :new.updated_on := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION', 'APP_USER'), user);
    if inserting then
        :new.row_version := 1;
        :new.created_on  := :new.updated_on;
        :new.created_by  := :new.updated_by;
    elsif updating then
        :new.row_version := nvl(:old.row_version, 0) + 1;
    end if;
end;
/

create or replace trigger pos_supplier_ledger_biu
    before insert or update on pos_supplier_ledger for each row
begin
    :new.updated_on := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION', 'APP_USER'), user);
    if inserting then
        :new.row_version := 1;
        :new.created_on  := :new.updated_on;
        :new.created_by  := :new.updated_by;
    elsif updating then
        :new.row_version := nvl(:old.row_version, 0) + 1;
    end if;
end;
/

create or replace trigger pos_settings_biu
    before insert or update on pos_settings for each row
begin
    :new.updated_on := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION', 'APP_USER'), user);
    if inserting then
        :new.row_version := 1;
        :new.created_on  := :new.updated_on;
        :new.created_by  := :new.updated_by;
    elsif updating then
        :new.row_version := nvl(:old.row_version, 0) + 1;
    end if;
end;
/

create or replace trigger pos_audit_log_biu
    before insert or update on pos_audit_log for each row
begin
    :new.updated_on := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION', 'APP_USER'), user);
    if inserting then
        :new.row_version := 1;
        :new.created_on  := :new.updated_on;
        :new.created_by  := :new.updated_by;
    elsif updating then
        :new.row_version := nvl(:old.row_version, 0) + 1;
    end if;
end;
/

prompt >> 01_pos_schema_ddl.sql completed successfully.
