prompt --application/set_environment
set define off verify off feedback off
whenever sqlerror exit sql.sqlcode rollback;
--------------------------------------------------------------------------------
--
-- Oracle APEX Application Export File (FIXED - NO ORA-06502)
-- Application: 101 - MyPOS Commercial Retail POS
-- Parsing Schema: WKSP_SHIVAM143WORKSPACE
--
--------------------------------------------------------------------------------
begin
wwv_flow_imp.import_begin (
 p_version_yyyy_mm_dd=>'2024.05.31'
,p_release=>'24.1.0'
,p_default_workspace_id=>null
,p_default_application_id=>101
,p_default_id_offset=>0
,p_default_owner=>nvl(wwv_flow_imp.g_owner, 'WKSP_SHIVAM143WORKSPACE')
);
end;
/
prompt --application/delete_application
begin
wwv_flow_imp.component_begin (
 p_version_yyyy_mm_dd=>'2024.05.31'
,p_release=>'24.1.0'
,p_default_workspace_id=>null
,p_default_application_id=>101
,p_default_id_offset=>0
,p_default_owner=>nvl(wwv_flow_imp.g_owner, 'WKSP_SHIVAM143WORKSPACE')
);
wwv_flow_imp.component_end;
end;
/
prompt --application/create_application
begin
wwv_flow_imp.component_begin (
 p_version_yyyy_mm_dd=>'2024.05.31'
,p_release=>'24.1.0'
,p_default_workspace_id=>null
,p_default_application_id=>101
,p_default_id_offset=>0
,p_default_owner=>nvl(wwv_flow_imp.g_owner, 'WKSP_SHIVAM143WORKSPACE')
);
wwv_flow_imp_shared.create_flow(
 p_id=>101
,p_owner=>nvl(wwv_flow_imp.g_owner, 'WKSP_SHIVAM143WORKSPACE')
,p_name=>'MyPOS - Commercial Retail POS'
,p_alias=>'MYPOS'
,p_page_view_logging=>'YES'
,p_page_view_cache_mode=>'DISABLED'
,p_theme_id=>42
,p_theme_version=>'24.1'
,p_home_page=>1
,p_login_page=>1
);
wwv_flow_imp.component_end;
end;
/
prompt --application/pages/page_00001
begin
wwv_flow_imp.component_begin (
 p_version_yyyy_mm_dd=>'2024.05.31'
,p_release=>'24.1.0'
,p_default_workspace_id=>null
,p_default_application_id=>101
,p_default_id_offset=>0
,p_default_owner=>nvl(wwv_flow_imp.g_owner, 'WKSP_SHIVAM143WORKSPACE')
);
wwv_flow_imp_page.create_page(
 p_id=>1
,p_name=>'POS / Billing Terminal'
,p_alias=>'POS'
,p_step_title=>'MyPOS - Commercial Retail POS'
,p_page_is_public_y_n=>'Y'
);
wwv_flow_imp_page.create_page_plug(
 p_id=>101001101
,p_page_id=>1
,p_plug_name=>'POS Cashier Terminal'
,p_plug_display_sequence=>10
,p_plug_display_point=>'BODY'
,p_plug_source_type=>'NATIVE_STATIC_CONTENT'
,p_plug_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'<!-- =============================================================================',
'     MYPOS ORACLE APEX - CASHIER POS BILLING SCREEN (EXACT IMAGE 1 UI)',
'     HOW TO USE IN ORACLE APEX:',
'     1. Open your APEX Application -> Go to Page 1 (Home) or Create Page 3 in Page Designer.',
'     2. In the Left Pane (Components), Right-Click on the old Cards Region -> Click Delete.',
'     3. Right-Click ''Content Body'' -> Select ''Create Region''.',
'        - Title: Cashier POS Terminal',
'        - Type: Static Content',
'     4. In the Right Pane under ''Source'' -> Paste this ENTIRE file content.',
'     5. Under Page Attributes (Top Node) -> Set Page Template: ''Minimal (No Navigation)''',
'     6. Click ''Save & Run'' (Play Button ▶️) on the top right!',
'     ============================================================================= -->',
'',
'<style>',
'/* Scoped POS Cashier Styles matching Image 1 exactly */',
'.pos-container-wrap {',
'  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;',
'  color: #1e293b;',
'  margin: -16px;',
'  background: #f1f5f9;',
'  min-height: calc(100vh - 80px);',
'  padding: 16px;',
'  box-sizing: border-box;',
'}',
'',
'.pos-main-layout {',
'  display: grid;',
'  grid-template-columns: 1fr 370px;',
'  gap: 16px;',
'  align-items: start;',
'}',
'',
'/* Left Catalog Panel */',
'.pos-catalog-panel {',
'  background: #ffffff;',
'  border: 1px solid #e2e8f0;',
'  border-radius: 8px;',
'  padding: 16px;',
'  box-shadow: 0 1px 3px rgba(0,0,0,0.05);',
'}',
'',
'.pos-search-header {',
'  display: flex;',
'  gap: 10px;',
'  align-items: center;',
'  margin-bottom: 14px;',
'  flex-wrap: wrap;',
'}',
'',
'.pos-customer-select {',
'  padding: 8px 12px;',
'  font-size: 0.85rem;',
'  border: 1px solid #cbd5e1;',
'  border-radius: 6px;',
'  background: #ffffff;',
'  font-weight: 500;',
'  min-width: 220px;',
'  color: #0f172a;',
'}',
'',
'.pos-btn {',
'  padding: 8px 14px;',
'  border-radius: 6px;',
'  font-size: 0.85rem;',
'  font-weight: 600;',
'  cursor: pointer;',
'  border: 1px solid transparent;',
'  transition: all 0.15s;',
'  display: inline-flex;',
'  align-items: center;',
'  justify-content: center;',
'  gap: 6px;',
'}',
'',
'.pos-btn-outline {',
'  background: #ffffff;',
'  border-color: #cbd5e1;',
'  color: #334155;',
'}',
'.pos-btn-outline:hover { background: #f8fafc; border-color: #94a3b8; }',
'',
'.pos-btn-primary {',
'  background: #1e40af;',
'  color: #ffffff;',
'}',
'.pos-btn-primary:hover { background: #1d4ed8; }',
'',
'.pos-btn-success {',
'  background: #10b981;',
'  color: #ffffff;',
'  font-size: 1.05rem;',
'  font-weight: 700;',
'}',
'.pos-btn-success:hover { background: #059669; }',
'',
'.pos-search-input {',
'  flex: 1;',
'  min-width: 200px;',
'  padding: 8px 14px;',
'  font-size: 0.875rem;',
'  border: 1px solid #cbd5e1;',
'  border-radius: 6px;',
'  outline: none;',
'}',
'.pos-search-input:focus { border-color: #1e40af; box-shadow: 0 0 0 2px rgba(30,64,175,0.15); }',
'',
'/* Category Pills */',
'.pos-category-chips {',
'  display: flex;',
'  gap: 8px;',
'  overflow-x: auto;',
'  padding-bottom: 8px;',
'  margin-bottom: 16px;',
'  scrollbar-width: thin;',
'}',
'',
'.pos-chip {',
'  padding: 6px 16px;',
'  border-radius: 20px;',
'  background: #f8fafc;',
'  border: 1px solid #e2e8f0;',
'  font-size: 0.825rem;',
'  font-weight: 600;',
'  color: #475569;',
'  cursor: pointer;',
'  white-space: nowrap;',
'  transition: all 0.15s ease;',
'}',
'.pos-chip:hover { background: #e2e8f0; color: #0f172a; }',
'.pos-chip.active {',
'  background: #1e40af;',
'  color: #ffffff;',
'  border-color: #1e40af;',
'}',
'',
'/* Product Cards Grid */',
'.pos-product-grid {',
'  display: grid;',
'  grid-template-columns: repeat(auto-fill, minmax(130px, 1fr));',
'  gap: 14px;',
'  max-height: 560px;',
'  overflow-y: auto;',
'  padding: 4px;',
'}',
'',
'.pos-product-card {',
'  background: #ffffff;',
'  border: 1px solid #e2e8f0;',
'  border-radius: 8px;',
'  padding: 12px 8px;',
'  text-align: center;',
'  cursor: pointer;',
'  transition: all 0.2s ease;',
'  display: flex;',
'  flex-direction: column;',
'  justify-content: space-between;',
'  user-select: none;',
'  box-shadow: 0 1px 2px rgba(0,0,0,0.03);',
'}',
'',
'.pos-product-card:hover {',
'  border-color: #1e40af;',
'  transform: translateY(-2px);',
'  box-shadow: 0 4px 10px rgba(30,64,175,0.12);',
'}',
'',
'.pos-product-card:active { transform: scale(0.97); }',
'',
'.pos-product-icon-wrap {',
'  height: 52px;',
'  display: flex;',
'  align-items: center;',
'  justify-content: center;',
'  font-size: 2.2rem;',
'  margin-bottom: 6px;',
'}',
'',
'.pos-product-name {',
'  font-size: 0.875rem;',
'  font-weight: 700;',
'  color: #0f172a;',
'  margin-bottom: 4px;',
'  white-space: nowrap;',
'  overflow: hidden;',
'  text-overflow: ellipsis;',
'}',
'',
'.pos-product-price {',
'  font-size: 0.95rem;',
'  font-weight: 800;',
'  color: #1e40af;',
'  margin-bottom: 2px;',
'}',
'',
'.pos-product-stock {',
'  font-size: 0.725rem;',
'  color: #64748b;',
'  font-weight: 500;',
'}',
'',
'/* Right Cart Sidebar */',
'.pos-cart-panel {',
'  background: #ffffff;',
'  border: 1px solid #e2e8f0;',
'  border-radius: 8px;',
'  display: flex;',
'  flex-direction: column;',
'  box-shadow: 0 1px 3px rgba(0,0,0,0.05);',
'  position: sticky;',
'  top: 16px;',
'}',
'',
'.pos-cart-header {',
'  display: flex;',
'  justify-content: space-between;',
'  align-items: center;',
'  padding: 14px 16px;',
'  border-bottom: 1px solid #e2e8f0;',
'  font-weight: 700;',
'  font-size: 0.95rem;',
'  color: #0f172a;',
'}',
'',
'.pos-customer-info-box {',
'  padding: 10px 14px;',
'  background: #f8fafc;',
'  border-bottom: 1px solid #e2e8f0;',
'}',
'',
'.pos-customer-info-title {',
'  display: flex;',
'  justify-content: space-between;',
'  align-items: center;',
'  font-size: 0.75rem;',
'  font-weight: 700;',
'  color: #64748b;',
'  text-transform: uppercase;',
'  margin-bottom: 6px;',
'}',
'',
'.pos-customer-fields {',
'  display: grid;',
'  grid-template-columns: 1fr 1fr;',
'  gap: 8px;',
'}',
'',
'.pos-customer-input {',
'  width: 100%;',
'  padding: 6px 8px;',
'  font-size: 0.8rem;',
'  border: 1px solid #cbd5e1;',
'  border-radius: 4px;',
'  box-sizing: border-box;',
'}',
'',
'/* Cart Items Container */',
'.pos-cart-items {',
'  min-height: 220px;',
'  max-height: 300px;',
'  overflow-y: auto;',
'  padding: 8px 12px;',
'}',
'',
'.pos-empty-cart {',
'  display: flex;',
'  flex-direction: column;',
'  align-items: center;',
'  justify-content: center;',
'  height: 200px;',
'  color: #94a3b8;',
'  text-align: center;',
'  padding: 20px;',
'}',
'',
'.pos-empty-cart-icon {',
'  font-size: 3rem;',
'  margin-bottom: 8px;',
'  opacity: 0.6;',
'}',
'',
'.pos-cart-item-row {',
'  display: flex;',
'  align-items: center;',
'  justify-content: space-between;',
'  padding: 8px 0;',
'  border-bottom: 1px solid #f1f5f9;',
'  font-size: 0.85rem;',
'}',
'',
'.pos-cart-item-name {',
'  font-weight: 600;',
'  color: #1e293b;',
'  flex: 1;',
'  padding-right: 8px;',
'  white-space: nowrap;',
'  overflow: hidden;',
'  text-overflow: ellipsis;',
'}',
'',
'.pos-cart-item-controls {',
'  display: flex;',
'  align-items: center;',
'  gap: 6px;',
'}',
'',
'.pos-qty-btn {',
'  width: 24px;',
'  height: 24px;',
'  border-radius: 4px;',
'  border: 1px solid #cbd5e1;',
'  background: #f8fafc;',
'  cursor: pointer;',
'  font-weight: bold;',
'  display: flex;',
'  align-items: center;',
'  justify-content: center;',
'  font-size: 0.85rem;',
'}',
'.pos-qty-btn:hover { background: #e2e8f0; }',
'',
'.pos-cart-item-qty {',
'  font-weight: 700;',
'  min-width: 18px;',
'  text-align: center;',
'}',
'',
'.pos-cart-item-price {',
'  font-weight: 700;',
'  min-width: 60px;',
'  text-align: right;',
'  color: #0f172a;',
'}',
'',
'.pos-del-btn {',
'  background: transparent;',
'  border: none;',
'  color: #ef4444;',
'  cursor: pointer;',
'  padding: 2px 6px;',
'  font-size: 0.9rem;',
'}',
'',
'/* Cart Summary */',
'.pos-cart-summary {',
'  padding: 14px 16px;',
'  background: #f8fafc;',
'  border-top: 1px solid #e2e8f0;',
'}',
'',
'.pos-summary-row {',
'  display: flex;',
'  justify-content: space-between;',
'  font-size: 0.85rem;',
'  color: #64748b;',
'  margin-bottom: 6px;',
'}',
'',
'.pos-summary-total {',
'  display: flex;',
'  justify-content: space-between;',
'  font-size: 1.25rem;',
'  font-weight: 800;',
'  color: #0f172a;',
'  border-top: 1px solid #cbd5e1;',
'  padding-top: 8px;',
'  margin-top: 6px;',
'}',
'',
'/* Cart Actions */',
'.pos-cart-actions {',
'  padding: 12px 16px;',
'  display: grid;',
'  grid-template-columns: 1fr 1fr 2fr;',
'  gap: 8px;',
'  border-top: 1px solid #e2e8f0;',
'}',
'',
'/* Checkout Modal */',
'.pos-modal-overlay {',
'  position: fixed;',
'  inset: 0;',
'  background: rgba(15, 23, 42, 0.6);',
'  display: none;',
'  align-items: center;',
'  justify-content: center;',
'  z-index: 99999;',
'}',
'.pos-modal-card {',
'  background: #ffffff;',
'  border-radius: 12px;',
'  width: 90%;',
'  max-width: 440px;',
'  padding: 24px;',
'  box-shadow: 0 20px 25px -5px rgba(0, 0, 0, 0.2);',
'}',
'</style>',
'',
'<div class="pos-container-wrap">',
'  <div class="pos-main-layout">',
'    ',
'    <!-- LEFT PANEL: CATALOG & SEARCH -->',
'    <div class="pos-catalog-panel">',
'      <!-- Search & Customer Bar -->',
'      <div class="pos-search-header">',
'        <select id="pos-cust-select" class="pos-customer-select" onchange="posCustomerChanged()">',
'          <option value="walkin">Walk-in Customer (9999999999)</option>',
'          <option value="anand" selected>Anand (7589445644)</option>',
'          <option value="sharma">Sharma Ji (9876543210)</option>',
'        </select>',
'        <button type="button" class="pos-btn pos-btn-outline" onclick="addNewCustomerPrompt()">+ New</button>',
'        <input type="text" id="pos-product-search" class="pos-search-input" placeholder="🔍 Scan / Search Product (F2)" oninput="filterProducts()" />',
'        <button type="button" class="pos-btn pos-btn-primary" onclick="browseAllProducts()">Browse (F4)</button>',
'      </div>',
'',
'      <!-- Category Filter Pills -->',
'      <div class="pos-category-chips" id="pos-chips-bar">',
'        <button type="button" class="pos-chip active" onclick="setCategory(''ALL'', this)">All Products</button>',
'        <button type="button" class="pos-chip" onclick="setCategory(''Dairy'', this)">Dairy</button>',
'        <button type="button" class="pos-chip" onclick="setCategory(''Bakery'', this)">Bakery</button>',
'        <button type="button" class="pos-chip" onclick="setCategory(''Snacks'', this)">Snacks</button>',
'        <button type="button" class="pos-chip" onclick="setCategory(''Beverages'', this)">Beverages</button>',
'        <button type="button" class="pos-chip" onclick="setCategory(''Food'', this)">Food</button>',
'        <button type="button" class="pos-chip" onclick="setCategory(''Household'', this)">Household</button>',
'        <button type="button" class="pos-chip" onclick="setCategory(''Personal Care'', this)">Personal Care</button>',
'      </div>',
'',
'      <!-- Product Cards Grid -->',
'      <div class="pos-product-grid" id="pos-grid-container">',
'        <!-- Rendered dynamically by JavaScript -->',
'      </div>',
'    </div>',
'',
'    <!-- RIGHT PANEL: STICKY CURRENT CART -->',
'    <div class="pos-cart-panel">',
'      <div class="pos-cart-header">',
'        <span>Current Cart (<span id="cart-item-count">0</span>)</span>',
'        <button type="button" class="pos-btn pos-btn-outline" style="padding:4px 10px; font-size:0.8rem;" onclick="emptyCart()">Clear</button>',
'      </div>',
'',
'      <!-- Customer Quick Box -->',
'      <div class="pos-customer-info-box">',
'        <div class="pos-customer-info-title">',
'          <span>👤 CUSTOMER INFO</span>',
'          <span style="color:#0284c7; cursor:pointer; font-weight:700;" onclick="addNewCustomerPrompt()">New Customer</span>',
'        </div>',
'        <div class="pos-customer-fields">',
'          <input type="text" id="cart-cust-name" class="pos-customer-input" placeholder="Customer Name" value="Anand" />',
'          <input type="tel" id="cart-cust-mobile" class="pos-customer-input" placeholder="Mobile No" value="7589445644" />',
'        </div>',
'      </div>',
'',
'      <!-- Items List -->',
'      <div class="pos-cart-items" id="pos-cart-list">',
'        <div class="pos-empty-cart" id="pos-cart-empty-view">',
'          <div class="pos-empty-cart-icon">🛒</div>',
'          <div style="font-weight:700; color:#475569; font-size:1rem; margin-bottom:4px;">Cart is empty</div>',
'          <div style="font-size:0.8rem; line-height:1.4;">Click any product card or scan barcode to add items</div>',
'        </div>',
'      </div>',
'',
'      <!-- Summary -->',
'      <div class="pos-cart-summary">',
'        <div class="pos-summary-row">',
'          <span>Sub Total:</span>',
'          <span id="cart-subtotal-val">₹ 0.00</span>',
'        </div>',
'        <div class="pos-summary-row">',
'          <span>GST (Est):</span>',
'          <span id="cart-gst-val">₹ 0.00</span>',
'        </div>',
'        <div class="pos-summary-total">',
'          <span>Total:</span>',
'          <span id="cart-total-val" style="color:#0f172a;">₹ 0.00</span>',
'        </div>',
'      </div>',
'',
'      <!-- Actions -->',
'      <div class="pos-cart-actions">',
'        <button type="button" class="pos-btn pos-btn-outline" onclick="holdCurrentBill()">Hold</button>',
'        <button type="button" class="pos-btn pos-btn-outline" onclick="emptyCart()">Draft</button>',
'        <button type="button" class="pos-btn pos-btn-success" onclick="openCheckoutModal()">Pay (F12)</button>',
'      </div>',
'    </div>',
'',
'  </div>',
'</div>',
'',
'<!-- CHECKOUT PAYMENT MODAL -->',
'<div class="pos-modal-overlay" id="checkout-modal">',
'  <div class="pos-modal-card">',
'    <div style="display:flex; justify-content:space-between; align-items:center; margin-bottom:16px;">',
'      <h3 style="margin:0; font-size:1.2rem; color:#0f172a;">Complete Payment</h3>',
'      <button type="button" onclick="closeCheckoutModal()" style="border:none; background:transparent; font-size:1.4rem; cursor:pointer;">&times;</button>',
'    </div>',
'    <div style="background:#f8fafc; padding:12px; border-radius:8px; margin-bottom:16px; border:1px solid #e2e8f0;">',
'      <div style="display:flex; justify-content:space-between; font-weight:700; font-size:1.1rem;">',
'        <span>Amount Payable:</span>',
'        <span id="modal-pay-amount" style="color:#10b981;">₹ 0.00</span>',
'      </div>',
'    </div>',
'    <div style="margin-bottom:16px;">',
'      <label style="display:block; font-size:0.8rem; font-weight:700; margin-bottom:6px; color:#475569;">Payment Method:</label>',
'      <div style="display:grid; grid-template-columns: repeat(3, 1fr); gap:8px;">',
'        <button type="button" class="pos-btn pos-btn-primary" onclick="processPayment(''CASH'')">💵 Cash</button>',
'        <button type="button" class="pos-btn pos-btn-primary" onclick="processPayment(''UPI'')">📱 UPI / QR</button>',
'        <button type="button" class="pos-btn pos-btn-primary" onclick="processPayment(''CARD'')">💳 Card</button>',
'      </div>',
'    </div>',
'    <button type="button" class="pos-btn pos-btn-outline" style="width:100%;" onclick="closeCheckoutModal()">Cancel</button>',
'  </div>',
'</div>',
'',
'<script>',
'// Commercial Product Master Dataset matching Image 1',
'var POS_PRODUCTS = [',
'  { id: 1, name: "Milk", category: "Dairy", price: 52.00, stock: 43, icon: "🥛", barcode: "890103001" },',
'  { id: 2, name: "Bread", category: "Bakery", price: 35.00, stock: 30, icon: "🍞", barcode: "890103002" },',
'  { id: 3, name: "Biscuits", category: "Snacks", price: 20.00, stock: 53, icon: "🍪", barcode: "890103003" },',
'  { id: 4, name: "Maggi", category: "Food", price: 15.00, stock: 39, icon: "🍜", barcode: "890103004" },',
'  { id: 5, name: "Soft Drink", category: "Beverages", price: 45.00, stock: 25, icon: "🥤", barcode: "890103005" },',
'  { id: 6, name: "Chips", category: "Snacks", price: 25.00, stock: 33, icon: "🍟", barcode: "890103006" },',
'  { id: 7, name: "Cooking Oil", category: "Household", price: 120.00, stock: 20, icon: "🍾", barcode: "890103007" },',
'  { id: 8, name: "Basmati Rice", category: "Food", price: 60.00, stock: 50, icon: "🍚", barcode: "890103008" },',
'  { id: 9, name: "Tata Salt", category: "Household", price: 10.00, stock: 10, icon: "📦", barcode: "890103009" },',
'  { id: 10, name: "Shampoo", category: "Personal Care", price: 85.00, stock: 18, icon: "🧴", barcode: "890103010" }',
'];',
'',
'var currentCategory = "ALL";',
'var cartItems = [];',
'',
'// Initialize Product Grid',
'function renderGrid() {',
'  var grid = document.getElementById("pos-grid-container");',
'  if (!grid) return;',
'  var searchInput = document.getElementById("pos-product-search");',
'  var search = (searchInput ? searchInput.value : "").toLowerCase().trim();',
'  grid.innerHTML = "";',
'',
'  var filtered = POS_PRODUCTS.filter(function(p) {',
'    var matchesCat = (currentCategory === "ALL" || p.category.toLowerCase() === currentCategory.toLowerCase());',
'    var matchesSearch = (!search || p.name.toLowerCase().indexOf(search) > -1 || p.barcode.indexOf(search) > -1);',
'    return matchesCat && matchesSearch;',
'  });',
'',
'  if (filtered.length === 0) {',
'    grid.innerHTML = ''<div style="grid-column:1/-1; text-align:center; padding:30px; color:#94a3b8;">No products found</div>'';',
'    return;',
'  }',
'',
'  filtered.forEach(function(item) {',
'    var card = document.createElement("div");',
'    card.className = "pos-product-card";',
'    card.onclick = function() { addToCart(item.id); };',
'    card.innerHTML = ',
'      ''<div class="pos-product-icon-wrap">'' + item.icon + ''</div>'' +',
'      ''<div class="pos-product-name" title="'' + item.name + ''">'' + item.name + ''</div>'' +',
'      ''<div class="pos-product-price">₹ '' + item.price.toFixed(2) + ''</div>'' +',
'      ''<div class="pos-product-stock">Stock: '' + item.stock + ''</div>'';',
'    grid.appendChild(card);',
'  });',
'}',
'',
'function setCategory(cat, el) {',
'  currentCategory = cat;',
'  var chips = document.querySelectorAll(".pos-chip");',
'  chips.forEach(function(c) { c.classList.remove("active"); });',
'  if (el) el.classList.add("active");',
'  renderGrid();',
'}',
'',
'function filterProducts() {',
'  renderGrid();',
'}',
'',
'function addToCart(productId) {',
'  var prod = POS_PRODUCTS.find(function(p) { return p.id === productId; });',
'  if (!prod) return;',
'',
'  var existing = cartItems.find(function(ci) { return ci.id === productId; });',
'  if (existing) {',
'    existing.qty += 1;',
'  } else {',
'    cartItems.push({',
'      id: prod.id,',
'      name: prod.name,',
'      price: prod.price,',
'      qty: 1',
'    });',
'  }',
'  renderCart();',
'}',
'',
'function updateCartQty(productId, delta) {',
'  var item = cartItems.find(function(ci) { return ci.id === productId; });',
'  if (!item) return;',
'  item.qty += delta;',
'  if (item.qty <= 0) {',
'    removeCartItem(productId);',
'  } else {',
'    renderCart();',
'  }',
'}',
'',
'function removeCartItem(productId) {',
'  cartItems = cartItems.filter(function(ci) { return ci.id !== productId; });',
'  renderCart();',
'}',
'',
'function emptyCart() {',
'  cartItems = [];',
'  renderCart();',
'}',
'',
'function renderCart() {',
'  var list = document.getElementById("pos-cart-list");',
'  var countBadge = document.getElementById("cart-item-count");',
'  var subtotalEl = document.getElementById("cart-subtotal-val");',
'  var gstEl = document.getElementById("cart-gst-val");',
'  var totalEl = document.getElementById("cart-total-val");',
'',
'  if (!list) return;',
'',
'  var totalCount = 0;',
'  var subtotal = 0;',
'',
'  cartItems.forEach(function(ci) {',
'    totalCount += ci.qty;',
'    subtotal += (ci.price * ci.qty);',
'  });',
'',
'  var gst = subtotal * 0.05; // 5% GST estimate',
'  var grandTotal = subtotal + gst;',
'',
'  if (countBadge) countBadge.textContent = totalCount;',
'  if (subtotalEl) subtotalEl.textContent = "₹ " + subtotal.toFixed(2);',
'  if (gstEl) gstEl.textContent = "₹ " + gst.toFixed(2);',
'  if (totalEl) totalEl.textContent = "₹ " + grandTotal.toFixed(2);',
'',
'  if (cartItems.length === 0) {',
'    list.innerHTML = ',
'      ''<div class="pos-empty-cart">'' +',
'        ''<div class="pos-empty-cart-icon">🛒</div>'' +',
'        ''<div style="font-weight:700; color:#475569; font-size:1rem; margin-bottom:4px;">Cart is empty</div>'' +',
'        ''<div style="font-size:0.8rem; line-height:1.4;">Click any product card or scan barcode to add items</div>'' +',
'      ''</div>'';',
'    return;',
'  }',
'',
'  var html = '''';',
'  cartItems.forEach(function(ci) {',
'    var lineTotal = ci.price * ci.qty;',
'    html += ',
'      ''<div class="pos-cart-item-row">'' +',
'        ''<div class="pos-cart-item-name" title="'' + ci.name + ''">'' + ci.name + ''</div>'' +',
'        ''<div class="pos-cart-item-controls">'' +',
'          ''<button type="button" class="pos-qty-btn" onclick="updateCartQty('' + ci.id + '', -1)">-</button>'' +',
'          ''<span class="pos-cart-item-qty">'' + ci.qty + ''</span>'' +',
'          ''<button type="button" class="pos-qty-btn" onclick="updateCartQty('' + ci.id + '', 1)">+</button>'' +',
'        ''</div>'' +',
'        ''<div class="pos-cart-item-price">₹ '' + lineTotal.toFixed(2) + ''</div>'' +',
'        ''<button type="button" class="pos-del-btn" onclick="removeCartItem('' + ci.id + '')" title="Remove item">&times;</button>'' +',
'      ''</div>'';',
'  });',
'  list.innerHTML = html;',
'}',
'',
'function openCheckoutModal() {',
'  if (cartItems.length === 0) {',
'    alert("Please add items to cart before checkout!");',
'    return;',
'  }',
'  var totalText = document.getElementById("cart-total-val").textContent;',
'  document.getElementById("modal-pay-amount").textContent = totalText;',
'  document.getElementById("checkout-modal").style.display = "flex";',
'}',
'',
'function closeCheckoutModal() {',
'  document.getElementById("checkout-modal").style.display = "none";',
'}',
'',
'function processPayment(mode) {',
'  var total = document.getElementById("cart-total-val").textContent;',
'  var custName = document.getElementById("cart-cust-name").value || "Walk-in Customer";',
'  closeCheckoutModal();',
'  alert("✅ Payment Successful via " + mode + "!\nAmount: " + total + "\nCustomer: " + custName + "\nBill Generated Successfully.");',
'  emptyCart();',
'}',
'',
'function holdCurrentBill() {',
'  if (cartItems.length === 0) return;',
'  alert("Active bill saved on Hold.");',
'}',
'',
'function addNewCustomerPrompt() {',
'  var name = prompt("Enter New Customer Name:");',
'  if (name) {',
'    var phone = prompt("Enter 10-digit Mobile Number:");',
'    document.getElementById("cart-cust-name").value = name;',
'    if (phone) document.getElementById("cart-cust-mobile").value = phone;',
'  }',
'}',
'',
'function posCustomerChanged() {',
'  var sel = document.getElementById("pos-cust-select");',
'  if (sel.value === "anand") {',
'    document.getElementById("cart-cust-name").value = "Anand";',
'    document.getElementById("cart-cust-mobile").value = "7589445644";',
'  } else if (sel.value === "sharma") {',
'    document.getElementById("cart-cust-name").value = "Sharma Ji";',
'    document.getElementById("cart-cust-mobile").value = "9876543210";',
'  } else {',
'    document.getElementById("cart-cust-name").value = "Walk-in Customer";',
'    document.getElementById("cart-cust-mobile").value = "9999999999";',
'  }',
'}',
'',
'function browseAllProducts() {',
'  setCategory("ALL", document.querySelector(".pos-chip"));',
'  document.getElementById("pos-product-search").value = "";',
'  renderGrid();',
'}',
'',
'// Keyboard Shortcuts (F2: Search, F12: Checkout)',
'window.addEventListener("keydown", function(e) {',
'  if (e.key === "F2") {',
'    e.preventDefault();',
'    var s = document.getElementById("pos-product-search");',
'    if (s) s.focus();',
'  } else if (e.key === "F12") {',
'    e.preventDefault();',
'    openCheckoutModal();',
'  }',
'});',
'',
'// Auto-run on load',
'setTimeout(function() {',
'  renderGrid();',
'  renderCart();',
'}, 200);',
'</script>'
))
);
wwv_flow_imp.component_end;
end;
/
prompt --application/end_environment
begin
wwv_flow_imp.import_end(p_auto_install_sup_obj => false);
commit;
end;
/
